### ISSUE TITLE
STS policy filename served over HTTPS should include "id" field

### ISSUE THREAD

**Issue by eyeofthenico** [mrisher/smtp-sts#62] opened 2016-07-19 12:52 UTC
Per https://tools.ietf.org/html/draft-ietf-uta-mta-sts-01 section 3.3 (Policy Discovery & Authentication):
The policy is served from a "well known" URI: "https://policy.mta-sts.example.com/.well-known/mta-sts/current".  To consider the policy as valid, the "policy_id" field in the policy MUST match the "id" field in the DNS TXT record under "_mta_sts".

This policy is always served from "current" location. As a consequence, this results in mismatch between "id" from DNS (possibly cached) and policy file when updated.
I propose to actually host policy in file tied to "id", for instance "$(id).json".
Servers should be keeping the old policies for up to STS DNS entry TTL expiration or risk for policy to be invalid and lose STS protection.

**Comment by prbinu** [comment] 2016-07-19 19:10
I think a well know location is desired, in that way we  don't have to force a DNS lookup.  One option would be to use current (or latest) as a symlink to the latest version.

**Comment by danmarg** [comment] 2016-08-02 12:24
Thanks for the commit. I think that mostly addresses Nico's point, but can we just get rid of /current? IMO it's extra complexity, and since you ought to do a TXT lookup anyway before fetching a policy, this isn't really extra DNS lookups, right?

**Comment by eyeofthenico** [comment] 2016-08-02 13:46
The idea was indeed to fully replace "current" with "${id}.json".
To summarize my perspective on it:
* "${id}.json": allows multiple policies at same time, prevents race condition.
* "current": works nicely with versioning system.
Given policies are going to be very static, I don't think versioning system is going to be a killer.
What do you think?

**Comment by prbinu** [comment] 2016-08-02 22:38
I think 'current' would be something useful to keep. In our case, it acts as an alternate way to discover/reach the policy. I would say DNS TXT is more of a convenience and the sync issue is actually a side effect of DNS STS record.

**Comment by danmarg** [comment] 2016-08-04 12:38
My point about TXT is that we don't probably ever expect anyone to get the HTTPS resource if the TXT hasn't changed (or else they may hammer the HTTPS endpoint!), and to see if it changed they have to get TXT first. So we can basically assume there's always a TXT lookup prior to an HTTPS GET anyway. (Regardless, the HTTPS GET itself involves resolving the hostname, so one more DNS lookup isn't going to kill us. ;) )

In any event, my concern is that with /current the fetched policy (if you fetch from "/current") may not match the ID in the TXT, which is just confusing. Removing this seems simpler and avoids that risk, no?

**Comment by prbinu** [comment] 2016-08-06 00:12
Slightly a different thought: The sync issue is the result of adding the version number to DNS TXT record. One suggestion would be to remove the version field from DNS STS record, and use the DNS STS record just to indicate the presence of a policy for that domain. Once the policy is cached, you may not need to do DNS TXT lookup, instead you directly refresh the policy from HTTPS location. I would expect the policy ideally get refreshed once a day.

Yes, this will end up in additional load on HTTPS endpoint. But I think that should be manageable when we take into consideration of number of compliant MTAs. In addition we may also increase refresh interval to reduce the load. 

By doing so, we no longer need to deal with any sync issues, and complex TTL and refresh problems.

I have shared few flow diagrams, and one of the diagram actually follow this logic.
(https://github.com/mrisher/smtp-sts/issues/72)

**Comment by danmarg** [comment] 2016-08-07 10:58
I commented on this on #72.

**Comment by danmarg** [comment] 2016-08-08 18:42
Sorry, let me repost a more clear comment here, with less rush. ;) 

It's true that you don't need to do a TXT lookup once you know a policy *should* exist, but it does essentially no harm. Is there a downside to Nico's suggestion? 

Conversely, how can we assume a policy will be refreshed once a day?

**Comment by prbinu** [comment] 2016-08-08 20:38
> It's true that you don't need to do a TXT lookup once you know a policy 
> should exist, but it does essentially no harm.

I think there is one. Lets say the sender is validating a policy that is already cached, and the validation fails because of an MX mismatch (the recipient changed MX to a 3rd party). In such cases, the sender needs to refresh the policy. The current flow checks DNS TXT record, and refresh policy only if the version is different from what is being cached. Adding DNS to the refresh flow adds an additional failure point. The failure may be due to (1) operations error  (2) an attack. In either case, the sender see no change in TXT record and the validation fails.

So the question is whether we need an additional failure point. As I get deep into implementation details , I'm looking out to simplify flows to make it clear, consistent, fail-safe and easy to implement. To be honest, i do not prefer mixing DNS TTLs with policy refresh. Ideally cache and refresh should be handled in application layer.

> Conversely, how can we assume a policy will be refreshed once a day?

We can indicate in the policy the suggested refresh interval. 
Again even if the policy validation fails (say, because of a policy change), the sender must fetch a fresh policy and try again before it gives up. That way we can always have a forced refresh.

**Comment by danmarg** [comment] 2016-08-08 20:53
A MITM who can inject spurious DNS records or prevent a DNS lookup can already induce a DoS, though. So I think only the operational complexity argument for failures is especially compelling here.

In any case, if we don't act on Nico's suggestion, I think we should do the converse and specify explicitly that the TXT ID field _need_ _not_ match that in the HTTPS policy text. That's the only point I want to address here: that if someone updates their TXT record but doesn't (yet) update their HTTPS policy, or vice-versa, the policy is not, during the interim, invalid. 

I see two ways to solve this, as described: either to use the TXT ID as the policy location, or to not require the TXT ID to match the policy ID. Both are extremely minor changes, but I believe it's worth solving this issue.

**Comment by prbinu** [comment] 2016-08-08 22:02
The suggestion you made above - does it align with https://github.com/mrisher/smtp-sts/issues/72 diagram [2] ?

Since a policy validation failure triggers a forced refresh, the impact of a sync issue is limited in the current design.

**Comment by danmarg** [comment] 2016-08-08 22:18
Sorry, which suggestion that I made? :)

The problem here is that as written, this isn't a validation failure (in the sense of a delivery validation failure) but rather a policy parse failure--if the policy ID doesn't match the TXT record, it appears to me to be invalid. (I'm not sure if this is what you're referring to, though.)

**Comment by prbinu** [comment] 2016-08-08 22:29
>policy parse failure--if the policy ID doesn't match the TXT record

Like I mentioned previously, this is not an issue if we do not store version-id in the DNS TXT. With that, the sole purpose of a DNS TXT record will be to indicate the presence of a policy.
Do you see any issue with this?

**Comment by danmarg** [comment] 2016-08-08 22:33
Ah, but I think this is why I mentioned the failure case: in the case of a policy validation failure, the sender will hammer the recipient HTTP endpoint looking for a new policy. 

If you recall, this is *why* we went with the whole TXT-version-indicator to begin with.

**Comment by prbinu** [comment] 2016-08-08 22:47
Yeah i remember. But then it is adding another layer of complexity. 

There are two types of failure cases:
1. An attack:
These conditions are rare, and that too, may not occur globally to all. So the traffic is not a concern here.

2. A policy change:
I think it is okay to directly hit HTTP endpoint; because in either case it has to hit this endpoint to get new policy.

**Comment by danmarg** [comment] 2016-08-08 22:52
The problem is that of hitting the http endpoint on every message. The purpose of the DNS version is to serve as an efficient, cacheable indicator. Why revisit what is a fairly significant part of the design now merely to avoid a mostly cosmetic change? I'm not saying we can't find alternatives to this proposal, but any alternative is likely substantially more complex than the proposal here. What's your main concern?

**Comment by prbinu** [comment] 2016-08-08 23:22
> The problem is that of hitting the http endpoint on every message

This is not correct. The policy will be cached after initial fetch. From my understanding, adding version-id in the TXT and comparing with policy-id in HTTP endpoint has limited value, but adds complexity.

What i'm suggesting is (repeating again): Use DNS TXT record for initial discovery, and fetch policies directly from there onwards; period. I think we have discussed all major scenarios in detail and analyzed the impact of directly hitting HTTP endpoint.

**Comment by danmarg** [comment] 2016-08-08 23:37
No, if the policy does not validate it is not cached.  And we require the sender to check for a new policy on every case of policy non-validation to ensure a new policy has not been published.

> A policy which has not ever been successfully authenticated MUST NOT be used to reject mail.

And

>  In "enforce" mode, however, sending MTAs MUST first check for a new
> authenticated policy before actually treating a message failure as
>  fatal.

So eliminating the DNS lookup on refresh *does* absolutely require (at least as the draft currently stands) that a sender make an HTTPS request *per* *message* *attempt*. 

I do think this bug is getting a bit off track, though. There's a very narrow (and extremely unlikely) scenario that Nicolas pointed out, namely the case that a sender fetching a new policy _during_ a recipient's rollout of a new policy could hit the DNS and HTTPS endpoints at a time when the two have different version numbers, thus failing to discover a valid policy. 

This is hardly a big deal, being both rare and self-recovering, but it seems easy enough to fix by either a) embedding the policy version into the URI or b) removing the version from the HTTPS resource entirely. Both are very minor changes and do not modify the state machine or security properties. 

I think maybe it would be better to start a different issue thread (or a thread on the UTA mailing list?) to discuss larger architectural changes. What do you think?

**Comment by prbinu** [comment] 2016-08-08 23:55
Sure, lets start a different thread and gather feedback from other contributors on policy refresh.

**Comment by danmarg** [comment] 2016-09-11 11:57
As discussed, we have instead removed the ID field from the .json to stop requiring a match there.

**Closed by danmarg** 2016-09-11 11:57 UTC
